### ISSUE TITLE
BadRequestException: 400

### ISSUE THREAD

**Issue by PeterBennink** [XMBomb/Spotify-Import-Artists#2]
I don't know whether this is due to me not having worked with Java that much and making some stupid mistake, or due to an actual error, but I keep getting the following for every artist/line in the res/artists.txt file:

```
com.wrapper.spotify.exceptions.BadRequestException: 400
	at com.wrapper.spotify.SpotifyHttpManager.handleErrorStatusCode(SpotifyHttpManager.java:178)
	at com.wrapper.spotify.SpotifyHttpManager.execute(SpotifyHttpManager.java:157)
	at com.wrapper.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:53)
	at com.wrapper.spotify.methods.AbstractRequest.getJson(AbstractRequest.java:34)
	at com.wrapper.spotify.methods.ArtistSearchRequest.get(ArtistSearchRequest.java:35)
	at App.lambda$main$0(App.java:44)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1494)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:591)
	at App.main(App.java:36)
```

**Comment by mbharanya** [comment]
Have you created a `res/auth-key.txt` file with the correct oauth token?
You can test it here https://developer.spotify.com/web-api/console/put-following/ with the 'try it' button

**Comment by PeterBennink** [comment]
Yeah I did! Just did it again with your new commit, now the error looks like this:

```
com.wrapper.spotify.exceptions.BadRequestException: 400
com.wrapper.spotify.exceptions.BadRequestException: 400
	at com.wrapper.spotify.SpotifyHttpManager.handleErrorStatusCode(SpotifyHttpManager.java:178)
	at com.wrapper.spotify.SpotifyHttpManager.execute(SpotifyHttpManager.java:157)
	at com.wrapper.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:53)
	at com.wrapper.spotify.methods.AbstractRequest.getJson(AbstractRequest.java:34)
	at com.wrapper.spotify.methods.ArtistSearchRequest.get(ArtistSearchRequest.java:35)
	at App.lambda$main$0(App.java:45)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1494)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:591)
	at App.main(App.java:36)
com.wrapper.spotify.exceptions.BadRequestException: 400
com.wrapper.spotify.exceptions.BadRequestException: 400
	at com.wrapper.spotify.SpotifyHttpManager.handleErrorStatusCode(SpotifyHttpManager.java:178)
	at com.wrapper.spotify.SpotifyHttpManager.execute(SpotifyHttpManager.java:157)
	at com.wrapper.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:53)
	at com.wrapper.spotify.methods.AbstractRequest.getJson(AbstractRequest.java:34)
	at com.wrapper.spotify.methods.ArtistSearchRequest.get(ArtistSearchRequest.java:35)
	at App.lambda$main$0(App.java:45)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1494)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:591)
	at App.main(App.java:36)
```

**Comment by mbharanya** [comment]
I can reproduce your issue. I think the spotify API changed.
I'll try upgrading to the new version of https://github.com/thelinmichael/spotify-web-api-java

**Comment by PeterBennink** [comment]
All right thank you!

**Comment by mbharanya** [comment]
Please test if it works and give me feedback that I can close this issue

**Comment by PeterBennink** [comment]
It works fully now! No errors at all now. Thanks so much!
